### ISSUE TITLE
Use 24h format not working?

### ISSUE THREAD

**Issue by robegamesios** [jnthas/clock-club#3]
hi, this is great thanks for making it. For me, the time format always shows 24 hour format regardless if the Yep is checked or not. Can you check please. thanks.

**Comment by andrecedik** [comment]
@robegamesios just a dumb question from my side as I had to figure this out myself when I started. Did you restart your device afterward? And does the UI then still show it as activated?

**Comment by robegamesios** [comment]
> @robegamesios just a dumb question from my side as I had to figure this out myself when I started. Did you restart your device afterward? And does the UI then still show it as activated?

the UI updates correctly but the LED panel still shows 24hr format regardless of the value. the endpoint is
http://xx.xx.xx.xx/set?use24hFormat=0 or 1. neither setting dont do anything.

**Comment by jnthas** [comment]
Hey guys, for Canvas themes, the time format is done using the ezTime format  
Canvas uses the ezTime to format the the date/time so you have the flexibility to define whatever you want
https://github.com/ropg/ezTime#getting-date-and-time

For example, the donkey kong theme is defined as ["H:i"](https://github.com/jnthas/clock-club/blob/f449abd214b193c4889723d746c227ee959867e0/shared/donkey-kong.json#L19C1-L20C1) that means it's 24h format. Capital H is for 24h, lower h is 12h.

**Comment by robegamesios** [comment]
> Hey guys, for Canvas themes, the time format is done using the ezTime format Canvas uses the ezTime to format the the date/time so you have the flexibility to define whatever you want https://github.com/ropg/ezTime#getting-date-and-time
> 
> For example, the donkey kong theme is defined as ["H:i"](https://github.com/jnthas/clock-club/blob/f449abd214b193c4889723d746c227ee959867e0/shared/donkey-kong.json#L19C1-L20C1) that means it's 24h format. Capital H is for 24h, lower h is 12h.

thanks @jnthas yep i can configure the JSON datetime content to what i need and it works (e.g. "content": "h:i:sa" == 3:34pm)
